import { readFileSync } from "node:fs";
import { join } from "node:path";
import { chromium } from "playwright";
import type { EmployeePayrollBreakdown, Invoice } from "@repo/types";

function formatInr(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
  }).format(amount);
}

function formatStatus(status: string): string {
  if (status === "not-generated") {
    return "Not Generated";
  }
  return status.charAt(0).toUpperCase() + status.slice(1);
}

function getTemplatePath(): string {
  return join(process.cwd(), "templates", "invoice.html");
}

function replacePlaceholders(
  template: string,
  replacements: Record<string, string>,
): string {
  return Object.entries(replacements).reduce(
    (html, [key, value]) =>
      html.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value),
    template,
  );
}

function buildEmployeeRows(breakdown: EmployeePayrollBreakdown[]): string {
  return breakdown
    .map(
      (row) => `<tr>
        <td>${row.employeeCode}</td>
        <td>${row.employeeName}</td>
        <td class="text-right">${row.present}</td>
        <td class="text-right">${formatInr(row.basicAmount)}</td>
        <td class="text-right">${formatInr(row.gradeAmount)}</td>
        <td class="text-right">${formatInr(row.otAmount)}</td>
        <td class="text-right">${formatInr(row.totalKr)}</td>
        <td class="text-right">${formatInr(row.pf)}</td>
        <td class="text-right">${formatInr(row.esi)}</td>
        <td class="text-right">${formatInr(row.payableAmount)}</td>
      </tr>`,
    )
    .join("\n");
}

function buildLegacyInvoiceHtml(invoice: Invoice): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Invoice ${invoice.invoiceNumber}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      color: #1a1a1a;
      padding: 48px;
      font-size: 14px;
      line-height: 1.5;
    }
    h1 { font-size: 24px; font-weight: 600; margin-bottom: 4px; }
    .subtitle { color: #666; margin-bottom: 32px; }
    table { width: 100%; border-collapse: collapse; margin-top: 16px; }
    th, td { padding: 12px 16px; text-align: left; border-bottom: 1px solid #e5e5e5; }
    th { font-weight: 600; background: #f9f9f9; width: 40%; }
    td { font-weight: 400; }
    .settled-yes { color: #16a34a; font-weight: 600; }
    .settled-no { color: #dc2626; font-weight: 600; }
    .footer { margin-top: 48px; color: #999; font-size: 12px; text-align: center; }
  </style>
</head>
<body>
  <h1>Invoice</h1>
  <p class="subtitle">${invoice.invoiceNumber} · ${invoice.monthYear}</p>
  <table>
    <tr><th>Invoice Number</th><td>${invoice.invoiceNumber}</td></tr>
    <tr><th>Month-Year</th><td>${invoice.monthYear}</td></tr>
    <tr><th>Total Bill</th><td>${formatInr(invoice.totalBill)}</td></tr>
    <tr><th>Service Charge</th><td>${formatInr(invoice.serviceCharge)}</td></tr>
    <tr><th>GST Amount</th><td>${formatInr(invoice.gst.amount)}</td></tr>
    <tr><th>GST Status</th><td>${formatStatus(invoice.gst.status)}</td></tr>
    <tr><th>ESIC Amount</th><td>${formatInr(invoice.esic.amount)}</td></tr>
    <tr><th>ESIC Status</th><td>${formatStatus(invoice.esic.status)}</td></tr>
    <tr>
      <th>Settled</th>
      <td class="${invoice.settled ? "settled-yes" : "settled-no"}">
        ${invoice.settled ? "Yes" : "No"}
      </td>
    </tr>
  </table>
  <p class="footer">Generated by Invoice Ledger</p>
</body>
</html>`;
}

function buildInvoiceHtml(invoice: Invoice): string {
  if (!invoice.totals || !invoice.employeeBreakdown?.length) {
    return buildLegacyInvoiceHtml(invoice);
  }

  const template = readFileSync(getTemplatePath(), "utf-8");
  const { totals } = invoice;

  return replacePlaceholders(template, {
    invoiceNumber: invoice.invoiceNumber,
    monthYear: invoice.monthYear,
    invoiceDate: invoice.invoiceDate ?? invoice.monthYear,
    employeeRows: buildEmployeeRows(invoice.employeeBreakdown),
    totalPf: formatInr(totals.totalPf),
    totalEsi: formatInr(totals.totalEsi),
    serviceCharge: formatInr(totals.serviceCharge),
    total: formatInr(totals.total),
    sgst: formatInr(totals.sgst),
    cgst: formatInr(totals.cgst),
    totalPayable: formatInr(totals.totalPayable),
  });
}

export async function generateInvoicePDF(invoice: Invoice): Promise<Buffer> {
  const html = buildInvoiceHtml(invoice);
  const executablePath = process.env.PLAYWRIGHT_CHROMIUM_PATH;

  const browser = await chromium.launch(
    executablePath ? { executablePath } : undefined,
  );

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "domcontentloaded" });
    const pdf = await page.pdf({ format: "A4", printBackground: true });
    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
